services:
  harvila:
    image: ghcr.io/splitbrain/harvila-laravel:latest
    container_name: harvila
    restart: unless-stopped
    volumes:
      - ./volumes/storage:/app/storage
    env_file: ".env"

    labels:
      traefik.enable: true
      traefik.http.routers.harvila.rule: Host(`harvila.splitbrain.net`)
      traefik.http.routers.harvila.tls.certresolver: letsencrypt

    networks:
      - traefik

  mailpit:
    image: axllent/mailpit
    container_name: harvila-mailpit
    restart: unless-stopped

    labels:
      traefik.enable: true
      traefik.http.routers.harvila-mailpit.rule: Host(`harvila-mailpit.splitbrain.net`)
      traefik.http.routers.harvila-mailpit.tls.certresolver: letsencrypt
      traefik.http.services.harvila-mailpit.loadbalancer.server.port: 8025

    networks:
      - traefik

networks:
  traefik:
    name: traefik
