services:
  rafinfo:
    image: joseluisq/static-web-server:2-alpine
    container_name: rafinfo
    restart: unless-stopped
    user: 1004:1004
    volumes:
      - ./volumes/htdocs:/public
      - ./conf/config.toml:/etc/config.toml

    environment:
      SERVER_IGNORE_HIDDEN_FILES: true
      SERVER_CONFIG_FILE: /etc/config.toml

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rafinfo.rule=Host(`www.rafinfo.de`) || Host(`rafinfo.de`)"
      - "traefik.http.routers.rafinfo.tls.certresolver=letsencrypt"
      - "traefik.http.routers.rafinfo.middlewares=redirect-to-www@file"
    networks:
      - traefik

networks:
  traefik:
    name: traefik
