services:
  splitbrain:
    image: dokuwiki/dokuwiki:stable
    container_name: splitbrain
    user: 1005:1005 # splitbrain
    restart: unless-stopped
    volumes:
       - ./volumes/storage:/storage
       - ./conf/htaccess:/var/www/html/.htaccess

    labels:
      traefik.enable: true
      traefik.http.routers.splitbrain.rule: Host(`www.splitbrain.org`) || Host(`splitbrain.org`)
      traefik.http.routers.splitbrain.tls.certresolver: letsencrypt
      traefik.http.routers.splitbrain.middlewares: redirect-to-www@file, splitbrain-static-redir@docker
      traefik.http.services.splitbrain.loadbalancer.server.port: 8080


      # Note: all dollar signs need to be doubled for escaping.
      traefik.http.middlewares.splitbrain-static-redir.redirectregex.regex: "^https://www.splitbrain.org/_static/(.*)"
      traefik.http.middlewares.splitbrain-static-redir.redirectregex.replacement: "https://stuff.splitbrain.org/$${1}"
      traefik.http.middlewares.splitbrain-static-redir.redirectregex.permanent: true

      chadburn.enabled: "true"
      chadburn.job-exec.linkblog.schedule: "@daily"
      chadburn.job-exec.linkblog.command: "php /var/www/html/lib/plugins/linkblog/cron.php"
    networks:
      - traefik

networks:
  traefik:
    name: traefik
