services:
  splitbrain:
    image: chialab/php:8.2-apache
    container_name: splitbrain
    user: 1005:1005 # splitbrain
    restart: unless-stopped
    volumes:
      - ./volumes/htdocs:/var/www/html/
      - ./conf/php.ini:/usr/local/etc/php/conf.d/php.ini:ro

    labels:
      traefik.enable: true
      traefik.http.routers.splitbrain.rule: Host(`www.splitbrain.org`) || Host(`splitbrain.org`)
      traefik.http.routers.splitbrain.tls.certresolver: letsencrypt
      traefik.http.routers.splitbrain.middlewares: redirect-to-www@file

      chadburn.enabled: "true"
      chadburn.job-exec.linkblog.schedule: "@daily"
      chadburn.job-exec.linkblog.command: "php /var/www/html/lib/plugins/linkblog/cron.php"
    networks:
      - traefik

networks:
  traefik:
    name: traefik
