include:
  - traefik/docker-compose.yaml
  - chadburn/docker-compose.yaml
  - watchtower/docker-compose.yaml
  - borgmatic/docker-compose.yaml
  - monitoring/docker-compose.yaml

  - splitbrain/docker-compose.yaml
  - stuff/docker-compose.yaml
  - hazwiki/docker-compose.yaml
  - rafinfo/docker-compose.yaml
  - commie/docker-compose.yaml
  - bms/docker-compose.yaml
  - indieblog/docker-compose.yaml
  - mancx/docker-compose.yaml
  - ots/docker-compose.yaml
  - fedi/docker-compose.yaml

  - harvila/docker-compose.yaml

