services:
  backup:
    image: offen/docker-volume-backup:v2
    container_name: backup
    restart: unless-stopped
    environment:
      SSH_HOST_NAME: u408911.your-storagebox.de
      SSH_PORT: 23
      SSH_USER: u408911
      SSH_REMOTE_PATH: /home/backup/bitters.splitbrain.org
      BACKUP_EXCLUDE_REGEXP: /(logs?|cache)/
      BACKUP_FILENAME: backup-%Y-%m-%dT%H-%M-%S.tar.gz
      BACKUP_PRUNING_PREFIX: backup-
      BACKUP_RETENTION_DAYS: 3
      NOTIFICATION_URLS: smtp://172.17.0.1:25/?fromAddress=backup@splitbrain.org&toAddresses=splitbrain@gmail.com&starttls=false
      NOTIFICATION_LEVEL: info
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./conf/id_rsa:/root/.ssh/id_rsa
      - /srv:/backup/srv:ro  # backup the whole composer stack in /srv
      - /etc:/backup/etc:ro  # backup the host's config in /etc
      - /backup:/archive  # keep local copies in /backup

