http:
  middlewares:
    basicauth:
      basicAuth:
        users:
          - "{{ env "BASIC_AUTH_USER" }}:{{ env "BASIC_AUTH_PASSWORD" }}"
    redirect-to-www:
      redirectRegex:
        regex: "^https?://(?:www\\.)?(.+)"
        replacement: "https://www.$1"
        permanent: true
    blockpath:
      plugin:
        blockpath:
          regex:
            - "/\\.git/"
    crowdsec:
      plugin:
        crowdsec:
          enabled: true
          logLevel: INFO
          crowdsecMode: stream
          crowdsecLapiHost: crowdsec:8080
          crowdsecLapiScheme: http
          crowdsecLapiKey: '{{ env "CROWDSEC_BOUNCER_KEY" }}'
          crowdsecAppsecEnabled: true
          crowdsecAppsecHost: crowdsec:7422
          crowdsecAppsecFailureBlock: false
          crowdsecAppsecUnreachableBlock: false
          updateIntervalSeconds: 60
          defaultDecisionSeconds: 60
          clientTrustedIPs:
            - 10.0.0.0/8
            - 172.16.0.0/12
            - 192.168.0.0/16
