services:
  chadburn:
    image: premoweb/chadburn:latest
    container_name: chadburn
    restart: unless-stopped
    command: daemon
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./conf/chadburn.conf:/etc/chadburn.conf

