services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./volumes/traefik:/traefik
    environment:
      LEGO_DISABLE_CNAME_SUPPORT: true
      PORKBUN_SECRET_API_KEY: ${PORKBUN_SECRET_API_KEY}
      PORKBUN_API_KEY: ${PORKBUN_API_KEY}
      GANDIV5_API_KEY: ${GANDIV5_API_KEY}
      BASIC_AUTH_USER: ${BASIC_AUTH_USER}
      BASIC_AUTH_PASSWORD: ${BASIC_AUTH_PASSWORD}
    command:
      - "--configFile=/traefik/traefik.yaml"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.splitbrain.net`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik.middlewares=basicauth@file"

  whoami:
    image: traefik/whoami:latest
    container_name: whoami
    restart: unless-stopped
    command:
      - "--verbose"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.splitbrain.net`)"
      - "traefik.http.routers.whoami.tls.certresolver=letsencrypt"

    networks:
      - traefik

networks:
  traefik:
    name: traefik
