services:
  traefik:
    image: traefik:v3.1
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./conf:/traefik
      - ./volumes/cert:/cert
      - ./volumes/log:/log
    environment:
      TZ: Europe/Berlin
      LEGO_DISABLE_CNAME_SUPPORT: true
      PORKBUN_SECRET_API_KEY: ${PORKBUN_SECRET_API_KEY}
      PORKBUN_API_KEY: ${PORKBUN_API_KEY}
      GANDIV5_API_KEY: ${GANDIV5_API_KEY}
      BASIC_AUTH_USER: ${BASIC_AUTH_USER}
      BASIC_AUTH_PASSWORD: ${BASIC_AUTH_PASSWORD}
    command:
      - "--configFile=/traefik/traefik.yaml"
    labels:
      traefik.enable: true
      traefik.http.routers.traefik.rule: Host(`traefik.splitbrain.org`)
      traefik.http.routers.traefik.service: api@internal
      traefik.http.routers.traefik.tls.certresolver: letsencrypt
      traefik.http.routers.traefik.middlewares: basicauth@file

      chadburn.enabled: "true"
      chadburn.job-exec.traefik-logrotate.schedule: "@weekly"
      chadburn.job-exec.traefik-logrotate.command: "/traefik/logrotate.sh"

  goaccess:
    image: allinurl/goaccess
    container_name: goaccess
    restart: unless-stopped
    command: >
      /srv/logs/access.log
      -o /srv/report/index.html
      --agent-list
      --with-output-resolver
      --real-time-html
      --origin=https://goaccess.splitbrain.org
      --ws-url=wss://goaccess.splitbrain.org:443/live
      --log-format='TRAEFIKCLF'
      --time-format='%H:%M:%S'
      --date-format='%d/%b/%Y'
      --db-path=/srv/data
      --geoip-database=/srv/data/GeoLite2-City.mmdb
      --persist
      --restore
    volumes:
      - ./volumes/log:/srv/logs:ro
      - ./volumes/web:/srv/report
      - ./volumes/goaccess:/srv/data
    labels:
      traefik.enable: true
      traefik.http.routers.goaccess.rule: Host(`goaccess.splitbrain.org`) && Path(`/live`)
      traefik.http.routers.goaccess.tls.certresolver: letsencrypt
      traefik.http.routers.goaccess.middlewares: basicauth@file

      chadburn.enabled: "true"
      chadburn.job-exec.goaccess-citydb.schedule: "@monthly"
      chadburn.job-exec.goaccess-citydb.command: "wget -nv https://github.com/P3TERX/GeoLite.mmdb/raw/download/GeoLite2-City.mmdb -O /srv/data/GeoLite2-City.mmdb.tmp && mv /srv/data/GeoLite2-City.mmdb.tmp /srv/data/GeoLite2-City.mmdb"

    networks:
      - traefik

  goaccess-web:
    image: joseluisq/static-web-server:2-alpine
    container_name: goaccess-web
    restart: unless-stopped
    volumes:
      - ./volumes/web:/public
    environment:
      SERVER_IGNORE_HIDDEN_FILES: true
    labels:
      traefik.enable: true
      traefik.http.routers.goaccess-web.rule: Host(`goaccess.splitbrain.org`)
      traefik.http.routers.goaccess-web.tls.certresolver: letsencrypt
      traefik.http.routers.goaccess-web.middlewares: basicauth@file
    networks:
      - traefik

networks:
  traefik:
    name: traefik
