# traefik.yaml
global:
  checkNewVersion: true
  sendAnonymousUsage: false

entryPoints:
  web:
    address: ":8088"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":8443"

api:
  dashboard: true
  insecure: true

log:
  level: "INFO"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: "traefik"


certificatesResolvers:
  letsencrypt:
    acme:
      email: andi@splitbrain.org
      storage: "/traefik/letsencrypt.json"
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: web
